apiVersion: apps/v1
kind: Deployment
metadata: 
  name: demo-jenkins
  labels:
    app: demo-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-jenkins
  template:
    metadata:
      labels:
        app: demo-jenkins
    spec:
      containers:
        - name: demo-jenkins
          image: s0pheap/demo-jenkins:tageName
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: demo-jenkins-secret
---
apiVersion: v1
kind: Service
metadata:
  name: demo-jenkins
spec:
  type: NodePort
  selector:            
    app: demo-jenkins
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-jenkins-secret
type: Opaque
data:
  DB_NAME: ZGVtbw== #demo
  DB_PASSWORD: cGFzc3dvcmQ= #password
  DB_USER: cG9zdGdyZXM= #postgres
  DB_HOST: MTAuMTAwLjE2Ny4xMTM6NTQzMg== #10.100.167.113:5432