apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.name}}
type: Opaque
data:
  DB_NAME: {{ .Values.api.secret.db_name }}
  DB_PASSWORD: {{ .Values.api.secret.db_password }}
  DB_USER: {{ .Values.api.secret.db_user }}
  DB_HOST: {{ .Values.api.secret.db_host }}